### ISSUE TITLE
Create an empty play area

### ISSUE THREAD

**Issue by ViMuilu** [HegePI/LinguaSaga-Studios#4]
Add blank area where objects can be placed

**Comment by spoingus1** [comment]
Created a very basic environment with some character movement.

**Comment by spoingus1** [comment]
Set up a game environment with the chosen assets. For now, I have chosen [Cyberpunk City Asset-Pack by rafazcruz](https://rafazcruz.itch.io/cyberpunk-top-down-game-asset-pack) for the environment, however this is subject to change.

It's also possible that we use this assets in one level, and something else in another.
